In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr[0][1])  # Output: 2
print(arr[0, 1])  # Output: 2

print("Entire Row:", arr[0]) # Output: [1 2 3]
print("Entire Column:", arr[:,1]) # Output: [2 5]

[[1 2 3]
 [4 5 6]]
2
2
Entire Row: [1 2 3]
Entire Column: [2 5]


In [ ]:
arr2 = np.array([[7, 90, 89], [10, 5, 12]])
print("Element-wise Addition:\n", arr + arr2)
print("Element-wise Subtraction:\n", arr - arr2)
print("Element-wise Multiplication:\n", arr * arr2)
print("Element-wise Division:\n", arr / arr2)
arr2.sort(axis=0)   # Will sort the array according to the columns
print(arr2)
print(np.sort(arr2, axis=0))  # Will sort the array according to the columns
arr2.sort(axis=1)   # Will sort the array according to the rows
print(arr2)

Element-wise Addition:
 [[ 8 92 92]
 [14 10 18]]
Element-wise Subtraction:
 [[ -6 -88 -86]
 [ -6   0  -6]]
Element-wise Multiplication:
 [[  7 180 267]
 [ 40  25  72]]
Element-wise Division:
 [[0.14285714 0.02222222 0.03370787]
 [0.4        1.         0.5       ]]
[[ 7  5 12]
 [10 90 89]]
[[ 5  7 12]
 [10 89 90]]


In [8]:
# Filter 
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[arr%2==0])  # Output: [ 2  4  6  8 10]
print(arr[arr>5])     # Output: [ 6  7  8  9 10]

# Filter by mask:
mask=arr>4
print(arr[mask])  # Output: [ 5  6  7  8  9 10]

[ 2  4  6  8 10]
[ 6  7  8  9 10]
[ 5  6  7  8  9 10]
