In [ ]:
import numpy as np
array=np.arange(10) # Creates an array of integers from 0 to 9
print(array)
array1=np.random.random((4,4))*100
array1=np.round(array1) # Rounding the values in the array to the nearest integer
print(array1)
array1=array1+50 # Scaler Addition - Adding a constant value to each element in the array
print(array1)
array1=array1-50 # Scaler Subtraction - Subtracting a constant value from each element in the array
print(array1)
array1=array1*2 # Scaler Multiplication - Multiplying each element in the array by a constant value
print(array1)
array1=array1/2 # Scaler Division - Dividing each element in the array by a constant value
print(array1)
print(np.max(array1)) # Finding the maximum value in the array
print(np.max(array1,axis=0)) # Finding the maximum value along the columns (axis=0)
print(np.max(array1,axis=1)) # Finding the maximum value along the rows (axis=1)
print(np.min(array1)) # Finding the minimum value in the array

In [ ]:
array1=np.arange(1,10).reshape(3,3) # Reshaping a 1D array into a 2D array with 3 rows and 3 columns
print(array1)
array2=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(array2)
array_sum=array1+array2 # Element-wise addition of two arrays
print(array_sum)
array_diff=array1-array2 # Element-wise subtraction of two arrays
print(array_diff)
array_prod=array1*array2 # Element-wise multiplication of two arrays
print(array_prod)
array_quot=array1/array2 # Element-wise division of two arrays
print(array_quot)

In [ ]:
data=np.random.random((4,4))*100
data=np.round(data)
data=data.astype(int) # Converting the data type of the array to integer
print(data)

print("Mean of the array:", np.mean(data)) # Calculating the mean of the array
print("Mean of the array along columns:", np.mean(data, axis=0)) # Calculating the mean along the columns (axis=0)
print("Mean of the array along rows:", np.mean(data, axis=1)) # Calculating the mean along the rows (axis=1)

print("Median of the array:", np.median(data)) # Calculating the median of the array
print("Median of the array along columns:", np.median(data, axis=0)) # Calculating the median along the columns (axis=0)
print("Median of the array along rows:", np.median(data, axis=1)) # Calculating the median along the rows (axis=1)
# The mean is the average of the numbers, while the median is the middle value when the numbers are sorted.

print("Standard Deviation of the array:", np.std(data)) # Calculating the standard deviation of the array
print("Standard Deviation of the array along columns:", np.std(data, axis=0)) # Calculating the standard deviation along the columns (axis=0)
print("Standard Deviation of the array along rows:", np.std(data, axis=1)) # Calculating the standard deviation along the rows (axis=1)
# Standard Deviation is a measure of the amount of variation or dispersion in a set of values. 
# A low standard deviation indicates that the values tend to be close to the mean, 
# while a high standard deviation indicates that the values are spread out over a wider range.

print("Variance of the array:", np.var(data)) # Calculating the variance of the array
# Variance is the average of the squared differences from the mean.

print(np.sin(30)) # Calculating the sine of 30 degrees
print(np.cos(30)) # Calculating the cosine of 30 degrees
print(np.tan(30)) # Calculating the tangent of 30 degrees

print(np.sin(45)) # Calculating the sine of 45 degrees
print(np.cos(45)) # Calculating the cosine of 45 degrees    
print(np.tan(45)) # Calculating the tangent of 45 degrees

In [ ]:
matrix1=np.random.random((3,3))*100
matrix1=np.round(matrix1)
matrix1=matrix1.astype(int)
print(matrix1)

matrix2=np.random.random((3,3))*100
matrix2=np.round(matrix2)   
matrix2=matrix2.astype(int)
print(matrix2)
# Matrix Multiplication (Dot Product) - The number of columns in the first matrix must be equal to the number of rows in the second matrix.
matrix_product=np.dot(matrix1,matrix2)
print(matrix_product)   

print("Log of the array:", np.log(matrix1)) # Calculating the natural logarithm of each element in the array
print("Exponential of the array:", np.exp(matrix1)) # Calculating the exponential of each element in the array
print("Square root of the array:", np.sqrt(matrix1)) # Calculating the square root of each element in the array

print("Unique elements in the array:", np.unique(matrix1)) # Finding the unique elements in the array

In [27]:
matrix=np.random.random((4,4))*100
print("original matrix:", matrix)
matrix2=np.round(matrix)
print("rounded matrix:", matrix2)

matrix3=np.ceil(matrix) # Rounding up each element in the array to the nearest integer
print("ceiling matrix:", matrix3)

matrix4=np.floor(matrix) # Rounding down each element in the array to the nearest integer
print("floor matrix:", matrix4)

original matrix: [[40.71370374 32.51313362 56.81659418 27.74525679]
 [29.25051655 48.09576232 34.73841646 21.02313866]
 [99.77664707 35.48677378 27.85625071 64.37350652]
 [64.1196552  42.47417728 72.92367528 21.83404996]]
rounded matrix: [[ 41.  33.  57.  28.]
 [ 29.  48.  35.  21.]
 [100.  35.  28.  64.]
 [ 64.  42.  73.  22.]]
ceiling matrix: [[ 41.  33.  57.  28.]
 [ 30.  49.  35.  22.]
 [100.  36.  28.  65.]
 [ 65.  43.  73.  22.]]
floor matrix: [[40. 32. 56. 27.]
 [29. 48. 34. 21.]
 [99. 35. 27. 64.]
 [64. 42. 72. 21.]]


In [30]:
# Transpose of a matrix - Flipping the matrix over its diagonal, switching the rows and columns.
arr=np.arange(1,13).reshape(3,4)
print("Original matrix:\n", arr)
transposed_arr=np.transpose(arr)
print("Transposed matrix:\n", transposed_arr)

# Slicing a 2D array - Extracting a portion of the array based on specified indices.
sliced_arr=arr[1:3, 1:4] # Extracting rows 1 to 2 and columns 1 to 3
print("Sliced array:\n", sliced_arr)
sliced_arr2=arr[:, 1:3] # Extracting all rows and columns 1 to 2
print("Sliced array 2:\n", sliced_arr2)

arr1=np.ravel(arr) # Flattening the array into a 1D array
print("Flattened array:", arr1)

Original matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transposed matrix:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Sliced array:
 [[ 6  7  8]
 [10 11 12]]
Sliced array 2:
 [[ 2  3]
 [ 6  7]
 [10 11]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Stacking arrays - Combining multiple arrays along a specified axis.

arr=np.arange(1,10).reshape(3,3)
print("Array 1:\n", arr)
arr2=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Array 2:\n", arr2)
stacked_array=np.hstack((arr,arr2)) # Stacking arrays horizontally (column-wise)
print("Stacked array (horizontal):\n", stacked_array)
# We can stack multiple arrays together using the same functions (hstack, vstack, etc.) by passing them as tuples.
print("Stacking multiple arrays:", np.hstack((arr, arr2, arr))) # Stacking arr, arr2, and arr horizontally

stacked_array2=np.vstack((arr,arr2)) # Stacking arrays vertically (row-wise)
print("Stacked array (vertical):\n", stacked_array2)

stack_arraay=np.stack((arr,arr2), axis=1) # Stacking arrays along a new axis (depth-wise)
print("Stacked array (depth-wise):\n", stack_arraay)

Array 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Stacked array (horizontal):
 [[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]
Stacking multiple arrays: [[ 1  2  3 10 20 30  1  2  3]
 [ 4  5  6 40 50 60  4  5  6]
 [ 7  8  9 70 80 90  7  8  9]]
Stacked array (vertical):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]
Stacked array (depth-wise):
 [[[ 1  2  3]
  [10 20 30]]

 [[ 4  5  6]
  [40 50 60]]

 [[ 7  8  9]
  [70 80 90]]]


In [38]:
# Splitting arrays - Dividing an array into multiple sub-arrays based on specified indices or sections.
arr=np.arange(1,10).reshape(3,3)
print("Original array:\n", arr)
split_arr=np.split(arr, 3) # Splitting the array into 3 equal parts along the first axis (rows)
print("Split array:\n", split_arr)
split_arr=np.hsplit(arr, 3) # Splitting the array into 3 equal parts along the second axis (columns)
print("Split array along columns:\n", split_arr)
split_arr2=np.split(arr, 3, axis=1) # Splitting the array into 3 equal parts along the second axis (columns)
print("Split array along columns:\n", split_arr2)
split_arr3=np.vsplit(arr, 3) # Splitting the array into 3 equal parts along the first axis (rows)
print("Split array along rows:\n", split_arr3)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Split array:
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
Split array along columns:
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
Split array along columns:
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
Split array along rows:
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [35]:
# Iterating over a 2D array - Accessing each element in the array using loops.
arr= np.arange(1,10).reshape(3,3)
for i in arr:
    print(i) # Accessing each row in the array
for i in np.nditer(arr):
    print(i) # Accessing each element in the array using nditerator
arr2=np.arange(1,9).reshape(2,2,2)
for i in arr2:
    print(i) # Accessing each 2D sub-array in the 3D array
for i in np.nditer(arr2):
    print(i) # Accessing each element in the 3D array using nditerator

[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
1
2
3
4
5
6
7
8
