In [ ]:
# What is NumPy?

# NumPy is a Python library used for working with arrays.
# It also has functions for working in domain of linear algebra, fourier transform, and matrices.
# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
# NumPy stands for Numerical Python.
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
# The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

# NumPy arrays are stored at one continuous place in memory unlike lists,
# so processes can access and manipulate them very efficiently.
# This behavior is called locality of reference in computer science.

# NumPy is a Python library and is written partially in Python, but most of the parts
# that require fast computation are written in C or C++.

In [2]:
!pip install numpy

  Using cached numpy-2.4.5-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.5-cp314-cp314-win_amd64.whl (12.5 MB)


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
arr= np.array([1,2,3,4,5])   # Creates as array
print(arr)
print(type(arr)) 
# type(): This built-in Python function tells us the type of the object passed to it.
# Like in above code it shows that arr is numpy.ndarray type.
print(np.__version__)  # Returns the version of numpy that has been insatlled


[1 2 3 4 5]
<class 'numpy.ndarray'>
2.4.5


In [4]:
arr2=np.array((45,67,89,0))
print(arr2)

[45 67 89  0]


In [5]:
# Dimensions in Arrays

# A dimension in arrays is one level of array depth (nested arrays).

# 0-D Arrays:
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
arr_0=np.array(89)
print(arr_0)
print(f"Dimension of arr_0: {arr_0.ndim}")

# 1-D Arrays:
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
arr_1=np.array([12,23,34,45,56])
print(arr_1)
print(f"Dimension of arr_1: {arr_1.ndim}")

# 2-D Array
# An array that has 1-D arrays as its elements is called a 2-D array.
# These are often used to represent matrix or 2nd order tensors.
arr_2=np.array([[1,2,3],[4,5,6]])
print(arr_2)
print(f"Dimension of arr_2: {arr_2.ndim}")

# 3-D Array
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.
# These are often used to represent a 3rd order tensor.
arr_3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3)
print(f"Dimension of arr_3: {arr_3.ndim}")

# When the array is created, you can define the number of dimensions by using the ndmin argument.
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

89
Dimension of arr_0: 0
[12 23 34 45 56]
Dimension of arr_1: 1
[[1 2 3]
 [4 5 6]]
Dimension of arr_2: 2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension of arr_3: 3
[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [6]:
# Array Indexing: -- Indexes are given comma separated
arr_2=np.array([[1,2,3],[4,5,6]])
print(arr_2[0,2])

arr_3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3[1,1,2])  # 1- First Dimension, 1- Second Dimension 2-Third Dimension
# Value printed will be 12

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])
# Print the last element from the 2nd dim:


3
12
Last element from 2nd dim:  10


In [7]:
# Slicing arrays

# Slicing in python means taking elements from one given index to another given index.
# We pass slice instead of index like this: [start:end].
# We can also define the step, like this: [start:end:step].
# If we don't pass start its considered 0
# If we don't pass end its considered length of array in that dimension
# If we don't pass step its considered 1
arr1= np.array((12,23,34,45,56,67,78))
print(arr1[2:4])
print(arr1[:8])  # If last index is way too large than the end of the array 
                 # then elements are taken till last index
print(arr1[3:])  # prints the elemnts till the end of array
print(arr1[-3:-1])

[34 45]
[12 23 34 45 56 67 78]
[45 56 67 78]
[56 67]
