In [ ]:
# Datatypes in Numpy:
# NumPy has some extra data types, and refer to data types with one character, 
# like i for integers, u for unsigned integers etc
# Datatypes:
# i - integer       b - boolean          u - unsigned integer
# f - float         c - complex float    m - timedelta
# M - datetime      O - object           S - string
# U - unicode string                     V - fixed chunk of memory for other type ( void )

In [ ]:
import numpy as np
arr=np.array([34,67,89,90])
print(arr.dtype)
arr2=np.array(["apple","bananaqqqqqqqqqqqqqq"])  
# The number coming in front of dtype is the largest possible size of the array
print(arr2.dtype)

# Array creation using Array method, this method can have it's optional argument as dtype
arr3=np.array([1,2,39999,457], dtype='S')
print(arr3)
print(arr3.dtype)

# This will give an error Since aa cannot be converted into integer
# arr4=np.array(["aa","2","3"], dtype='i')  
arr4=np.array(["120","2","3"], dtype='i')  
print(arr4)
print(arr4.dtype)

# For i, u, f, S and U we can define size as well.

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

# : In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.


int64
<U20
[b'1' b'2' b'39999' b'457']
|S5
[120   2   3]
int32
[1 2 3 4]
int32


In [ ]:
# The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
# It allows you to convert the data type of an array to another data type.
arr=np.array([1.67, 3.45,5656.65])
newarr=arr.astype('i')
print(newarr.dtype)
print(newarr)

arr2=newarr.astype('f')
print(arr2.dtype)
print(arr2)
# arr3=newarr.astype('bool')
arr3=arr2.astype('bool')
print(arr3)
print(arr3.dtype)

arr4=arr3.astype('str')
print(arr4)
print(arr4.dtype)

int32
[   1    3 5656]
float32
[1.000e+00 3.000e+00 5.656e+03]
[ True  True  True]
bool
['True' 'True' 'True']
<U5
