In [ ]:
# Numpy lists are faster than normal lists because they are implemented in C and optimized for performance. 
# They also use less memory than normal lists because they store data in a contiguous block of memory,
# which allows for faster access and manipulation. 
# Additionally, NumPy arrays support vectorized operations, 
# which can further improve performance by allowing for operations to be performed on entire arrays at once,
# rather than element-wise.

import time
import numpy as np
start= time.time()
list1= [i*2 for i in range(1000000)]
end= time.time()
print("Time taken by list comprehension: ", end-start)
start= time.time()
list2=np.arange(1000000)*2
end= time.time()
print("Time taken by NumPy array: ", end-start)

Time taken by list comprehension:  0.06493520736694336
Time taken by NumPy array:  0.0038568973541259766


In [4]:
# Normal lists do not support vectorized operations, so when we perform an operation on a list, it is done element-wise. 
# For example, if we want to multiply each element of a list by 2,
# we would have to use a loop or a list comprehension to iterate through each element and perform the multiplication.
list1=[1,2,3]*2
print(list1)  # Output: [1, 2, 3, 1, 2, 3]

list2=np.array([1,2,3])*2
print(list2)  # Output: [2 4 6]

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [14]:
# NumPy provides several functions to create arrays with specific values.
# [] or () can be used to create a list or a tuple, 
# which can then be converted to a NumPy array using the np.array() function.
zeros=np.zeros((2,3))
print(zeros)
ones=np.ones([3,4])
print(ones)
sevens=np.full([2,4],7)
print(sevens)
random=np.random.random([3,4])   # np.random.random gives you random values between 0 and 1
print(random)

sequence=np.arange(0,10,3)  # arange gives you a sequence of numbers from start to end with a step size
print(sequence)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]]
[[0.00933059 0.5930334  0.04201016 0.16370729]
 [0.00214249 0.67298941 0.89294042 0.13127967]
 [0.59436164 0.16044917 0.13971435 0.36405254]]
[0 3 6 9]


In [16]:
# Vector - A vector is a one-dimensional array that represents a quantity with both magnitude and direction.
vector=np.array([1,2,3])
print(vector)
# Matrix - A matrix is a two-dimensional array that represents a rectangular array of numbers, symbols, or expressions, arranged in rows and columns.
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)   
# tensor - A tensor is a multi-dimensional array that can represent data with more than two dimensions.
tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])  # This will create a one-dimensional array with the specified elements.
print(np.shape(arr))  # This will return the shape of the array, which is (12,) indicating that it is a one-dimensional array with 12 elements.
print(np.ndim(arr))  # This will return the number of dimensions of the array, which is 1 for a one-dimensional array.
print(np.size(arr))  # This will return the total number of elements in the array, which is 12.
arr2=arr.reshape(3,4)  # This will reshape the one-dimensional array into a two-dimensional array with 3 rows and 4 columns.
print(arr2)
print(np.shape(arr2)) 
print(np.ndim(arr2))  
print(np.size(arr2)) 
arr21=arr2.transpose()  # This will transpose the array, which means that the rows and columns will be swapped.
print(arr21)
arr3=arr2.reshape(2,2,3)  # This will reshape the two-dimensional array into a three-dimensional array with 2 blocks, 2 rows, and 3 columns.    
print(arr3)
print(np.shape(arr3))
print(np.ndim(arr3))
print(np.size(arr3))
arr4=arr3.flatten()
print(arr4)
print(np.shape(arr4))
print(np.ndim(arr4))
print(np.size(arr4))
arr5=arr3.ravel() # ravel is similar to flatten but it returns a view of the original array whenever possible,
                  # which means that if you modify the raveled array, it will also modify the original array.
print(arr5)
print(np.shape(arr5))
print(np.ndim(arr5))
print(np.size(arr5))

(12,)
1
12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
12
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
12
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1
12
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1
12
